### ISSUE TITLE
bug when installing

### ISSUE THREAD

**Issue by Obliterous** [lisdude/toaststunt-documentation#6]
On a new DB:

@update-toaststunt-help
Do you want to update the help database ToastStunt Help Database (#86)? [Enter `yes' or `no']
yes
#20:_tolist (this == #20), line 12:  Task ran out of ticks
... called from #20:_tolist (this == #20), line 12
... called from #20:to_value (this == #20), line 12
... called from #57:@update-toaststunt-help, line 101
(End of traceback)

**Comment by lisdude** [comment]
Fixed with commit a3c906fee24cb738426585a115223e32be6aa7c6
